# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"  # or cron-based
    open-pull-requests-limit: 5
    cooldown:
      semver-patch-days: 7
      semver-minor-days: 14
      semver-major-days: 30
    ignore:
      - dependency-name: "@tauri-apps/api"
        versions: ["2.x"]
  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    cooldown:
      semver-patch-days: 14
      semver-minor-days: 30
