name: Lint Code
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Cache ESLint results
        uses: actions/cache@v3
        with:
          path: .eslintcache
          key: ${{ runner.os }}-eslint-${{ hashFiles('**/package-lock.json','**/.eslintrc.js','**/.eslintignore') }}
          restore-keys: |
            ${{ runner.os }}-eslint-

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint -- --cache --cache-strategy content --cache-location .eslintcache
